"""empty message

Revision ID: 20d455cecce
Revises: None
Create Date: 2015-07-02 15:26:08.057445

"""

# revision identifiers, used by Alembic.
revision = '20d455cecce'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('result_all', sa.String(), nullable=True),
    sa.Column('result_no_stop_words', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    ### end Alembic commands ###
